### ISSUE TITLE
Cannot Contribute !!!!!!

### ISSUE THREAD

**Issue by PooriaShahi** [sinabehmanesh/Laravel-deployment#5]
Hey man

I can't contribute in this project in any sort of ways. just leave github if you don't want any contribution.

**Comment by sinabehmanesh** [comment]
Hello dear @PooriaShahi  ,

i have sent an invitation to you, please accept if you will.
you will be added permanently to this project for your contribution.
wish to see your PRs!

kind regards,
Sina.
